### ISSUE TITLE
Component mapToState not receiving initial props or state

### ISSUE THREAD

**Issue by bruth** [damusix/riot-meiosis#1]
First off, thank you for putting this library together. So far it feels like a much simpler alternative to Redux.

The issue I am observing boils to these [few lines](https://github.com/damusix/riot-meiosis/blob/master/lib/connect.js#L57-L61). The state passed into `mapToState` has not been populated nor does it derive the state from `this` if/after an `onBeforeMount` function is defined. Likewise `mapToState` doesn't receive the props. The problem is selecting out the subset of the application state (via `getState()`) that is relevant to the component.

For example if had an app state like:

```json
{
  "items": {
    "a": { .. },
    "b": { .. },
  }
}
```

And had two components for `a` and `b` each with an id as a prop for that component, `mapToState` couldn't select down to the subset of the state.

I hope that makes sense and let me know if I am missing something or there is a different way of thinking about the problem. Thanks!

**Comment by damusix** [comment]
Fixed in https://github.com/damusix/riot-meiosis/commit/8980b1c53b888436d0c6902e5d4c94818cc501d9
